# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cbafc8d63fcef16553f613b60ab94b8a2684936fae12ddec62e0ae4da45c48ffe5dac87cd9dfa7625cb5fe6184bd3d3184ae39bca08de0cca6f10a1dae4ce34

test:
  secret_key_base: 47e5c36e97fc8fa9a5f9e4b590bda443fd6ef3b2341bd7b3a68710d2f5937906bf1a1041f516332a6616628d46b09216d6533298b8c73511bdc8ef02a85cff6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
